# 简介


机器人的空间描述主要是二维、三维的情况，空间某个点用向量表示，可以使用齐次变换矩阵来进行这种变换，因为旋转和平移的变换组合是一种仿射变换，所以齐次变换矩阵会比原空间增加一维，这也要求原空间的向量增加一维，这个维度一般不表示信息(用1来表示某个具体点，而0来表示方向向量)

In [3]:
import numpy as np

In [4]:
def get_rotation_z(theta_deg):
    """生成绕Z轴的旋转矩阵"""
    theta = np.radians(theta_deg)
    c, s = np.cos(theta), np.sin(theta)
    return np.array([
        [c, -s, 0],
        [s,  c, 0],
        [0,  0, 1]
    ])

In [5]:
def get_homogeneous_matrix(R, P):
    """组合旋转和平移生成4x4齐次变换矩阵"""
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = P
    return T

In [8]:
# --- 场景模拟 ---
# 机器人末端坐标系 {B} 相对于基坐标系 {A}:
# 1. 绕 Z 轴旋转 90 度
# 2. 沿 X 轴平移 2 米, 沿 Y 轴平移 1 米
R_AB = get_rotation_z(90)
P_AB = np.array([2, 1, 0])

T_AB = get_homogeneous_matrix(R_AB, P_AB)
P_B = np.array([1, 0, 0, 1])
P_A = T_AB @ P_B
print("变换矩阵 T_AB:\n", T_AB)
print("-" * 30)
print(f"点在局部坐标系 B: {P_B[:3]}")
print(f"点在全局坐标系 A: {P_A[:3]}")

变换矩阵 T_AB:
 [[ 6.123234e-17 -1.000000e+00  0.000000e+00  2.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
------------------------------
点在局部坐标系 B: [1 0 0]
点在全局坐标系 A: [2. 2. 0.]
